apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-model
  namespace: common-apps
spec:
  predictor:
    containers:
      - name: kserve-container
        image: <REGISTRY>/custom-model:<VERSION>
        imagePullPolicy: Always
