kind: ConfigMap
metadata:
creationTimestamp: "2022-06-08T08:38:00Z"
name: dex
namespace: auth

apiVersion: v1
  
data:
  config.yaml: |
    issuer: https://kubeflow.flexigrobots-h2020.eu/dex
    storage:
      type: kubernetes
      config:

    logger:
      level: "debug"
      format: text
  connectors:
  - type: github
    # Required field for connector id.
    id: github
    # Required field for connector name.
    name: GitHub
    config:
      # Credentials can be string literals or pulled from the environment.
      clientID: c70a650f8553537d8724
      clientSecret: *****afdb7de6
      redirectURI: https://kubeflow.flexigrobots-h2020.eu/dex/callback
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
  staticPasswords:
  - email: user@example.com
    hash: $2y$12$4K/VkmDd1q1Orb3xAt82zu8gk7Ad6ReFR4LCP9UeYE90NLiN9Df72
    # https://github.com/dexidp/dex/pull/1601/commits
    # FIXME: Use hashFromEnv instead
    username: user
    userID: "15841185641784"
  staticClients:
  # https://github.com/dexidp/dex/pull/1664
  - idEnv: OIDC_CLIENT_ID