apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: mosquitto
data:
  password.txt: |
    admin:$6$ZzV2eTzphC1tuiPw$5YHN5MusQoEzrjEx79byTeZVQZqMXp9F8ZziVAUrJdwq/SQj3jHf+tVN84KLKMGayEkjXO68UygFcaXz1SA3TQ==