name: Train Model
description: Trains a simple neural network

inputs:
- {name: Data, type: LocalPath, description: 'Path where data is stored.'}
outputs:
- {name: Accuracy, type: Float, description: 'Path where accuracy metric is stored'}

implementation:
  container:
    image: ghcr.io/flexigrobots-h2020/kubeflow-example-training:latest
    command: [
      python, train_model.py,

      --data,
      {inputPath: Data},

      --accuracy,
      {outputPath: Accuracy},

    ]