apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
  labels:
    app: minio
type: Opaque
stringData:
  MINIO_ROOT_USER: ## to be replaced by minio-user
<<<<<<< HEAD
  MINIO_ROOT_PASSWORD: ## to be replaced by minio-password
=======
  MINIO_ROOT_PASSWORD: ## to be replaced by minio-password

>>>>>>> master
